/**
 * Contact personas for seed data.
 * Each contact has a distinct voice and typical email patterns.
 */
export const CONTACT_TEMPLATES = [
  {
    name: "Sarah Chen",
    email: "sarah.chen@company.com",
    avatar_url: "https://i.pravatar.cc/150?u=sarah.chen@company.com",
    category: "primary" as const,
    voice: "professional, direct, technical",
  },
  {
    name: "Alex Rivera",
    email: "alex.rivera@gmail.com",
    avatar_url: "https://i.pravatar.cc/150?u=alex.rivera@gmail.com",
    category: "primary" as const,
    voice: "casual, friendly, uses emoji",
  },
  {
    name: "Mom",
    email: "margaret.w@outlook.com",
    avatar_url: "https://i.pravatar.cc/150?u=margaret.w@outlook.com",
    category: "primary" as const,
    voice: "warm, caring, slightly formal",
  },
  {
    name: "GitHub",
    email: "notifications@github.com",
    avatar_url: "https://logo.clearbit.com/github.com",
    category: "updates" as const,
    voice: "automated, concise",
  },
  {
    name: "Jira",
    email: "jira@company.atlassian.net",
    avatar_url: "https://logo.clearbit.com/atlassian.com",
    category: "updates" as const,
    voice: "automated, structured",
  },
  {
    name: "LinkedIn",
    email: "notifications@linkedin.com",
    avatar_url: "https://logo.clearbit.com/linkedin.com",
    category: "social" as const,
    voice: "professional networking",
  },
  {
    name: "Spotify",
    email: "no-reply@spotify.com",
    avatar_url: "https://logo.clearbit.com/spotify.com",
    category: "promotions" as const,
    voice: "upbeat, music-focused",
  },
  {
    name: "Chase Bank",
    email: "no-reply@chase.com",
    avatar_url: "https://logo.clearbit.com/chase.com",
    category: "updates" as const,
    voice: "formal, financial",
  },
  {
    name: "The Verge",
    email: "newsletter@theverge.com",
    avatar_url: "https://logo.clearbit.com/theverge.com",
    category: "forums" as const,
    voice: "journalistic, tech-savvy",
  },
  {
    name: "Dr. Patel's Office",
    email: "appointments@patelhealthcare.com",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=Dr.+Patel",
    category: "updates" as const,
    voice: "professional, medical",
  },
  {
    name: "David Kim",
    email: "d.kim@company.com",
    avatar_url: "https://i.pravatar.cc/150?u=d.kim@company.com",
    category: "primary" as const,
    voice: "professional, collaborative",
  },
  {
    name: "Figma",
    email: "notifications@figma.com",
    avatar_url: "https://logo.clearbit.com/figma.com",
    category: "updates" as const,
    voice: "design tool notifications",
  },
  {
    name: "Amazon",
    email: "shipment-tracking@amazon.com",
    avatar_url: "https://logo.clearbit.com/amazon.com",
    category: "promotions" as const,
    voice: "transactional, retail",
  },
  {
    name: "Rachel Torres",
    email: "rachel.t@gmail.com",
    avatar_url: "https://i.pravatar.cc/150?u=rachel.t@gmail.com",
    category: "primary" as const,
    voice: "friendly, enthusiastic",
  },
  {
    name: "Vercel",
    email: "notifications@vercel.com",
    avatar_url: "https://logo.clearbit.com/vercel.com",
    category: "updates" as const,
    voice: "deployment notifications",
  },
  {
    name: "Dad",
    email: "mike.lawner@gmail.com",
    avatar_url: "https://i.pravatar.cc/150?u=mike.lawner@gmail.com",
    category: "primary" as const,
    voice: "warm, proud, dad jokes, slightly long-winded",
  },
  {
    name: "Airbnb",
    email: "automated@airbnb.com",
    avatar_url: "https://logo.clearbit.com/airbnb.com",
    category: "updates" as const,
    voice: "transactional, hospitality",
  },
  {
    name: "Uber Eats",
    email: "noreply@ubereats.com",
    avatar_url: "https://logo.clearbit.com/ubereats.com",
    category: "promotions" as const,
    voice: "transactional, food delivery",
  },
  {
    name: "Prince Abubakar Tunde",
    email: "prince.tunde.royal@mail2world.com",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=Prince+Tunde",
    category: "promotions" as const,
    voice: "scam, overly formal, urgency",
  },
  {
    name: "Digital Growth Experts",
    email: "seo-results@digital-growth-x.biz",
    avatar_url: "https://api.dicebear.com/9.x/initials/svg?seed=DGE",
    category: "promotions" as const,
    voice: "spam, aggressive marketing, ALL CAPS",
  },
  {
    name: "Marcus Johnson",
    email: "marcus.j@gmail.com",
    avatar_url: "https://i.pravatar.cc/150?u=marcus.j@gmail.com",
    category: "primary" as const,
    voice: "casual, college buddy, nostalgic",
  },
] as const;
